name: Release

on:
   push:
     branches:
       - main

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Semantic release
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_DO_GITHUB }}
        uses: androzo/semantic-release@main
